#!/bin/bash

# Manual deployment script for BP Logistics Dashboard
# Run this if automated deployment fails

VPS_HOST="178.16.140.185"
DEPLOYMENT_PACKAGE="bp-dashboard-deployment-20250619_205927.tar.gz"

echo "🚀 BP Logistics Dashboard - Manual Deployment Helper"
echo "================================================="
echo ""
echo "Package ready: $DEPLOYMENT_PACKAGE"
echo "VPS Server: $VPS_HOST"
echo ""
echo "Manual deployment steps:"
echo ""
echo "1. Upload the deployment package:"
echo "   scp $DEPLOYMENT_PACKAGE root@$VPS_HOST:/tmp/"
echo ""
echo "2. SSH into the server:"
echo "   ssh root@$VPS_HOST"
echo ""
echo "3. Run these commands on the server:"
echo "   # Create backup"
echo "   cp -r /var/www/html /var/www/html_backup_\$(date +%Y%m%d_%H%M%S)"
echo ""
echo "   # Deploy new version"
echo "   cd /var/www/html"
echo "   rm -rf *"
echo "   tar -xzf /tmp/$DEPLOYMENT_PACKAGE"
echo ""
echo "   # Set permissions"
echo "   chown -R www-data:www-data /var/www/html"
echo "   chmod -R 755 /var/www/html"
echo "   find /var/www/html -type f -exec chmod 644 {} \;"
echo ""
echo "   # Restart Nginx"
echo "   systemctl reload nginx"
echo "   systemctl status nginx"
echo ""
echo "4. Test the deployment:"
echo "   Visit: https://bpsolutionsdashboard.com"
echo ""
echo "================================================="

# Try to upload automatically if possible
echo "Attempting automatic upload..."
echo "You may be prompted for the password: Viper123"
echo ""

scp $DEPLOYMENT_PACKAGE root@$VPS_HOST:/tmp/ && echo "✅ Upload successful!" || echo "❌ Upload failed - please upload manually"