#!/bin/bash

echo "Run these diagnostic commands on the VPS:"
echo ""
echo "ssh neal@178.16.140.185"
echo ""
echo "# Check if API is running"
echo "pm2 list"
echo ""
echo "# Test API locally"
echo "curl http://localhost:5001/health"
echo ""
echo "# Check for errors in logs"
echo "pm2 logs bp-logistics-api --lines 10"
echo ""
echo "# Check nginx error log"
echo "sudo tail -20 /var/log/nginx/error.log"
echo ""
echo "# Verify which port the API is using"
echo "cd /var/www/bp-logistics/backend"
echo "grep PORT .env"
echo ""
echo "# Check if server.js was properly updated"
echo "grep -n 'app.use.*limiter' src/server.js"