#!/bin/bash

echo "Quick fix to disable rate limiter temporarily:"
echo ""
echo "1. SSH to server:"
echo "   ssh neal@178.16.140.185"
echo ""
echo "2. Edit the server.js file:"
echo "   cd /var/www/bp-logistics/backend"
echo "   sudo nano src/server.js"
echo ""
echo "3. Find this line (around line 41):"
echo "   app.use('/api/', limiter)"
echo ""
echo "4. Comment it out by adding // at the beginning:"
echo "   // app.use('/api/', limiter)"
echo ""
echo "5. Save the file (Ctrl+X, then Y, then Enter)"
echo ""
echo "6. Restart the service:"
echo "   pm2 restart bp-logistics-api"
echo ""
echo "This will temporarily disable rate limiting and fix the 500 error."